// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKkStYPea0hwuhRfQ5iAZht0XDQyp0bf0',
    appId: '1:1030234475415:web:e4cc99bb2f18384bfb92d2',
    messagingSenderId: '1030234475415',
    projectId: 'inputformproject',
    authDomain: 'inputformproject.firebaseapp.com',
    storageBucket: 'inputformproject.firebasestorage.app',
    measurementId: 'G-Y598SJTHZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCepScsjKm-UiRxLHN5U2acmjxi5Ov8z8',
    appId: '1:1030234475415:android:cf5ca382be18d73afb92d2',
    messagingSenderId: '1030234475415',
    projectId: 'inputformproject',
    storageBucket: 'inputformproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_SmqiUCnaMFE2z3UxbPuTDdaWg5wTYE',
    appId: '1:1030234475415:ios:1247ebed520db3e5fb92d2',
    messagingSenderId: '1030234475415',
    projectId: 'inputformproject',
    storageBucket: 'inputformproject.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFirestoreProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKkStYPea0hwuhRfQ5iAZht0XDQyp0bf0',
    appId: '1:1030234475415:web:fe07d71ae38530a5fb92d2',
    messagingSenderId: '1030234475415',
    projectId: 'inputformproject',
    authDomain: 'inputformproject.firebaseapp.com',
    storageBucket: 'inputformproject.firebasestorage.app',
    measurementId: 'G-HD14BL7TX3',
  );
}
